### PR TITLE
Warn against misconceptions of the library

### PR DESCRIPTION
**Pull request by vemv**
While the proposed note is quite obvious in hindsight, I did in fact spend some time playing with Exact until I realised it wasn't the right tool for the job.

Cheers - Victor

### CODE REVIEW

**Comment by gfredericks** [comment]
When you say "there's no way to convert 2.2 to an exact representation", you mean it in the sense that the library doesn't offer a decimal parser, not that it's not capable of representing 2.2 exactly (e.g., with 22/10)?

I think the note as written can be misleading, since the floating point numbers that javascript and the JVM have literally cannot exactly represent 2.2, though exact can.

**Comment by vemv** [comment]
That seems right!

Feel free to close the PR in favor of a more accurate warning.

**Comment by gfredericks** [comment]
Let me know if anything about the wording I added seems inadequate.

**Comment by vemv** [comment]
👍 thanks for this one!

**Pull request closed without merging**
